<?php
$z[0]=Array("type","\r\n            <h3>[field:typename/]</h3>\r\n            ",175,263);
$z[0][4]['typeid']="2";
$z[1]=Array("channel","\r\n              <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n              ",297,439);
$z[1][4]['typeid']="2";
$z[1][4]['type']="son";
$z[2]=Array("type","\r\n            <h3>[field:typename/]</h3>\r\n            ",505,593);
$z[2][4]['typeid']="4";
$z[3]=Array("channel","\r\n              <li><a href='[field:typelink/]' title=\"[field:typename/]\">[field:typename/]</a></li>\r\n              ",627,795);
$z[3][4]['typeid']="4";
$z[3][4]['type']="son";
$z[4]=Array("type","\r\n            <h3>[field:typename/]</h3>\r\n            ",861,949);
$z[4][4]['typeid']="5";
$z[5]=Array("channel","\r\n              <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n              ",983,1125);
$z[5][4]['typeid']="5";
$z[5][4]['type']="son";
$z[6]=Array("global","",2328,2354);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("channel","\r\n            <li>>><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",2550,2687);
$z[7][4]['row']="6";
$z[7][4]['type']="top";
$z[8]=Array("flink"," \r\n        [field:link /] \r\n        ",2780,2876);
$z[8][4]['titlelen']="20";
$z[8][4]['row']="32";
$z[8][4]['type']="text";

?>