<?php
$z[0]=Array("global","",163,189);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",253,279);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",458,550);
$z[2][4]['name']="typeid";
$z[2][4]['runphp']="yes";
$z[3]=Array("channel","\r\n            <li><a  href='[field:typelink/]'>[field:typename/]</a></li>\r\n            ",595,807);
$z[3][4]['row']="6";
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[4]=Array("field","(@me==\"\")? @me=\" class='current' \":@me=\"\";",1276,1368);
$z[4][4]['name']="typeid";
$z[4][4]['runphp']="yes";
$z[5]=Array("channel","\r\n          <li><a  href='[field:typeurl/]'>[field:typename/]</a></li>\r\n          ",1411,1633);
$z[5][4]['type']="top";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";

?>