<?php
$z[0]=Array("global","",620,646);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",815,842);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",882,912);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",1619,1654);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n        <li><a href=\"\" title=\"1\"><img src=\"[field:picname/]\" /></a></li>\r\n        ",1756,1886);
$z[4][4]['row']="3";
$z[4][4]['typeid']="7";
$z[5]=Array("sql"," \r\n            \r\n            [field:content  function='cn_substr(html2text(@me),1000)'/]...\r\n            \r\n            ",2604,2794);
$z[5][4]['sql']="Select content from dede_arctype where id=2";
$z[6]=Array("type","\r\n        <div class=\"x12 text-center\" id=\"index_about_more\"><a href=\"[field:typelink/]\" >更&nbsp;多</a></div>\r\n        ",2825,2981);
$z[6][4]['typeid']="2";
$z[7]=Array("arclist","\r\n          <div class='xm3 xs6 xl12 pro_li'>\r\n            <div class='li_img'><i></i><img src='[field:picname/]' /></div>\r\n            <div class='li_txt'><a href='[field:arcurl/]' title='[field:title/] ' >\r\n              <h5>[field:title/] </h5>\r\n              <p></p>\r\n              </a></div>\r\n          </div>\r\n          ",3547,3919);
$z[7][4]['row']="8";
$z[7][4]['typeid']="4";
$z[8]=Array("type","<a href=\"[field:typelink/]\" >更&nbsp;多</a>",4007,4086);
$z[8][4]['typeid']="4";
$z[9]=Array("arclist","\r\n          <div class='xb6 xm12 xs12 xl12 new_li'><a href='[field:arcurl/]' title='[field:title/] '><i></i>\r\n            <div class='time'><span>8</span><span>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</span></div>\r\n            <h5>[field:title/] </h5>\r\n            <p></p>\r\n            </a></div>\r\n          ",4423,4782);
$z[9][4]['row']="4";
$z[9][4]['typeid']="1";
$z[10]=Array("type","<a href=\"[field:typelink/]\" >更&nbsp;多</a>",4849,4928);
$z[10][4]['typeid']="1";
$z[11]=Array("arclist","\r\n            <li><a title='[field:title/]'><img class='img-responsive' src='[field:picname/]' alt='[field:title/]' /></a></li>\r\n            ",5448,5637);
$z[11][4]['row']="10";
$z[11][4]['typeid']="17";
$z[12]=Array("include","",5743,5780);
$z[12][4]['filename']="footer.htm";

?>