<?php
$z[0]=Array("field","",382,401);
$z[0][4]['name']="title";
$z[1]=Array("global","",402,428);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",469,491);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",531,583);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1212,1247);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1523,1580);
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n          <li class=\"first_cat\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",1678,1955);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='first_cat'><a href='~typelink~' id='lsed'>~typename~</a></li>";
$z[7]=Array("field","",2024,2045);
$z[7][4]['name']="content";
$z[8]=Array("include","",2111,2148);
$z[8][4]['filename']="footer.htm";

?>