<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,469);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1229,1264);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n          <li class=\"first_cat\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",1644,1921);
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li class='first_cat'><a href='~typelink~' id='lsed'>~typename~</a></li>";
$z[6]=Array("list","\r\n            <li>\r\n              <div class=\"pro_img\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" alt=\"[field:title/]\"></a></div>\r\n              <div class=\"pro_title\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n            </li>\r\n            ",2095,2442);
$z[6][4]['pagesize']="8";
$z[7]=Array("pagelist","",2572,2638);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2744,2781);
$z[8][4]['filename']="footer.htm";

?>